apiVersion: v1
kind: Service
metadata:
  name: cowrie-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: cowrie
  ports:
    - protocol: TCP
      name: "ssh-port"
      port: 2222
      targetPort: 2222
    - protocol: TCP
      name: "telnet-23-port"
      port: 23
      targetPort: 2223
    - protocol: TCP
      name: "telnet-2223-port"
      port: 2223
      targetPort: 2223
