apiVersion: v1
kind: Pod
metadata:
  name: honeynet-cowrie
  labels:
    app: cowrie
spec:
  containers:
    - name: cowrie
      image: gcr.io/honeypots-network/honeynet-cowrie:0.2
      ports:
        - containerPort: 2222
          name: ssh
          protocol: TCP
